apiVersion: v1
kind: Service
metadata:
  name: ${{ values.component_id }}
  labels:
    app: ${{ values.component_id }}
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: ${{ values.port }}
    protocol: TCP
  selector:
    app: ${{ values.component_id }}
